/* Transplant extractor — pulls the ORIGINAL built page apart VERBATIM:
   - head+body <style> blocks   -> src/app/configurator.css   (byte-preserved, in order)
   - static body HTML           -> src/app/shell-body.json    (scripts/styles excluded)
   - the 5 <script> blocks      -> public/engine/*.js         (byte-preserved, in order)
   - script load order          -> src/app/shell-scripts.json
   Nothing is reformatted, prettified, or re-authored. */
import path from 'node:path';
import fs from 'node:fs';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, '../..');
const html = fs.readFileSync(path.join(ROOT, '8k-labels-package/dist/configurator.html'), 'utf8');

// --- collect real <style>/<script> element ranges (skip CDATA matches inside JS strings) ---
const blocks = [];
for (const m of html.matchAll(/<style[^>]*>([\s\S]*?)<\/style>/g)) {
  if (m[1].includes('CDATA')) continue; // template literals inside the engine JS
  blocks.push({ type: 'style', start: m.index, end: m.index + m[0].length, content: m[1] });
}
for (const m of html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g)) {
  blocks.push({ type: 'script', start: m.index, end: m.index + m[0].length, content: m[1] });
}
blocks.sort((a, b) => a.start - b.start);

// --- CSS: every style block, original order ---
const css = blocks.filter((b) => b.type === 'style').map((b) => b.content).join('\n');
fs.writeFileSync(path.join(ROOT, 'src/app/configurator.css'), css);
console.log('configurator.css:', css.length, 'bytes,', blocks.filter((b) => b.type === 'style').length, 'style blocks');

// --- scripts: byte-preserved files, document order ---
const SCRIPT_NAMES = ['shell.js', 'img-data.js', 'label-engine.js', 'editor-embed.js', 'image-gen.js'];
const scripts = blocks.filter((b) => b.type === 'script');
if (scripts.length !== SCRIPT_NAMES.length) {
  throw new Error(`expected ${SCRIPT_NAMES.length} scripts, found ${scripts.length}`);
}
const engineDir = path.join(ROOT, 'public/engine');
fs.mkdirSync(engineDir, { recursive: true });
scripts.forEach((s, i) => {
  fs.writeFileSync(path.join(engineDir, SCRIPT_NAMES[i]), s.content);
  console.log(SCRIPT_NAMES[i] + ':', s.content.length, 'bytes');
});
fs.writeFileSync(
  path.join(ROOT, 'src/app/shell-scripts.json'),
  JSON.stringify(SCRIPT_NAMES.map((n) => '/engine/' + n), null, 2)
);

// sanity: the inlined modules must equal the package src files (modulo the inliner's newlines)
for (const [i, srcName] of [[1, 'img-data.js'], [2, 'label-engine.js'], [3, 'editor-embed.js'], [4, 'image-gen.js']]) {
  const srcFile = fs.readFileSync(path.join(ROOT, '8k-labels-package/src', srcName), 'utf8');
  const same = scripts[i].content.trim() === srcFile.trim();
  console.log(`verbatim check ${srcName}:`, same ? 'IDENTICAL to src/' : 'DIFFERS from src/ (dist wins — using dist bytes)');
}

// --- body HTML: everything inside <body> minus the style/script elements ---
const bodyStart = html.indexOf('<body>') + '<body>'.length;
const bodyEnd = html.indexOf('</body>');
let cursor = bodyStart;
let bodyHtml = '';
for (const b of blocks) {
  if (b.start < bodyStart) continue;
  bodyHtml += html.slice(cursor, b.start);
  cursor = b.end;
}
bodyHtml += html.slice(cursor, bodyEnd);
if (/<script|<style/.test(bodyHtml)) throw new Error('body HTML still contains script/style tags');
// Emit as a TS module with every non-ASCII char \u-escaped: webpack's JSON-module
// inlining corrupts emoji (surrogate pairs), and escaped ASCII survives any toolchain.
const literal = JSON.stringify(bodyHtml).replace(
  /[\u007f-\uffff]/g,
  (c) => '\\u' + c.charCodeAt(0).toString(16).padStart(4, '0')
);
fs.writeFileSync(
  path.join(ROOT, 'src/app/shell-body.ts'),
  '// GENERATED by tests/parity/extract-shell.mjs — do not edit by hand.\n' +
    '// Byte-identical body HTML of 8k-labels-package/dist/configurator.html.\n' +
    'const html: string = ' + literal + ';\n' +
    'export default html;\n'
);
fs.rmSync(path.join(ROOT, 'src/app/shell-body.json'), { force: true });
console.log('shell-body.ts:', bodyHtml.length, 'chars of static HTML');
