/* GENERATED by tools/extract-templates.mjs from the owner's
   Layout_Options.pdf — do not edit by hand. Re-run the tool when he
   re-draws a template. Millimetres, measured from the TRIM's top-left
   (his 2 mm bleed is outside);
   sizes in points at the reference size. */

import type { Template } from "./templates";

export const TEMPLATES: Template[] = [
  {
    "id": "t01",
    "band": "classical",
    "refW": 100,
    "refH": 80,
    "art": {
      "kind": "rect",
      "x": 0,
      "y": 0,
      "w": 100,
      "h": 39.149
    },
    "texts": [
      {
        "fields": [
          "producer"
        ],
        "role": "secondary",
        "x": 50,
        "baseline": 46.226,
        "fromBottom": 33.774,
        "anchor": "bottom",
        "align": "center",
        "size": 13.01,
        "caps": true,
        "accent": false,
        "tracking": 0.22,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "GRAND VIN"
      },
      {
        "fields": [
          "wineName"
        ],
        "role": "hero",
        "x": 50,
        "baseline": 54.03,
        "fromBottom": 25.97,
        "anchor": "bottom",
        "align": "center",
        "size": 20,
        "caps": true,
        "accent": true,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "CHÂTEAU MARGAUX"
      },
      {
        "fields": [
          "appellation"
        ],
        "role": "secondary",
        "x": 50,
        "baseline": 59.855,
        "fromBottom": 20.145,
        "anchor": "bottom",
        "align": "center",
        "size": 14,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "Margaux AOC"
      },
      {
        "fields": [
          "classification"
        ],
        "role": "small",
        "x": 50,
        "baseline": 65.385,
        "fromBottom": 14.615,
        "anchor": "bottom",
        "align": "center",
        "size": 10,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Premier Grand Cru Classé"
      },
      {
        "fields": [
          "grape"
        ],
        "role": "small",
        "x": 50,
        "baseline": 68.562,
        "fromBottom": 11.438,
        "anchor": "bottom",
        "align": "center",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "Cabernet Sauvignon, Merlot"
      },
      {
        "fields": [
          "special"
        ],
        "role": "small",
        "x": 5,
        "baseline": 71.608,
        "fromBottom": 8.392,
        "anchor": "bottom",
        "align": "left",
        "size": 8,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Vieilles Vignes"
      },
      {
        "fields": [
          "regionCountry"
        ],
        "role": "small",
        "x": 94.6,
        "baseline": 71.608,
        "fromBottom": 8.392,
        "anchor": "bottom",
        "align": "right",
        "size": 8,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Bordeaux, France"
      },
      {
        "fields": [
          "wineTypeLine"
        ],
        "role": "small",
        "x": 5,
        "baseline": 75.138,
        "fromBottom": 4.862,
        "anchor": "bottom",
        "align": "left",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Dry Red Wine"
      },
      {
        "fields": [
          "alcVol"
        ],
        "role": "small",
        "x": 94.6,
        "baseline": 75.138,
        "fromBottom": 4.862,
        "anchor": "bottom",
        "align": "right",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Alc.: 13.5% / 750 ml."
      },
      {
        "fields": [
          "vintage"
        ],
        "role": "secondary",
        "x": 50,
        "baseline": 75.291,
        "fromBottom": 4.709,
        "anchor": "bottom",
        "align": "center",
        "size": 13,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "2018"
      }
    ]
  },
  {
    "id": "t02",
    "band": "classical",
    "refW": 100,
    "refH": 80,
    "art": {
      "kind": "oval",
      "x": 16.231,
      "y": 10.534,
      "w": 67.537,
      "h": 36.509
    },
    "texts": [
      {
        "fields": [
          "producer"
        ],
        "role": "secondary",
        "x": 50,
        "baseline": 9.136,
        "fromBottom": 70.864,
        "anchor": "top",
        "align": "center",
        "size": 10.03,
        "caps": true,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "GRAND VIN",
        "arc": {
          "cx": 49.999,
          "cy": 74.727,
          "r": 66.885,
          "up": true,
          "sweep": 22.49
        }
      },
      {
        "fields": [
          "wineName"
        ],
        "role": "hero",
        "x": 50,
        "baseline": 54.03,
        "fromBottom": 25.97,
        "anchor": "bottom",
        "align": "center",
        "size": 16,
        "caps": true,
        "accent": true,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "CHÂTEAU MARGAUX"
      },
      {
        "fields": [
          "appellation"
        ],
        "role": "secondary",
        "x": 50,
        "baseline": 59.502,
        "fromBottom": 20.498,
        "anchor": "bottom",
        "align": "center",
        "size": 14,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "Margaux AOC"
      },
      {
        "fields": [
          "classification"
        ],
        "role": "small",
        "x": 50,
        "baseline": 65.385,
        "fromBottom": 14.615,
        "anchor": "bottom",
        "align": "center",
        "size": 10,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Premier Grand Cru Classé"
      },
      {
        "fields": [
          "grape"
        ],
        "role": "small",
        "x": 50,
        "baseline": 68.562,
        "fromBottom": 11.438,
        "anchor": "bottom",
        "align": "center",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "Cabernet Sauvignon, Merlot"
      },
      {
        "fields": [
          "special"
        ],
        "role": "small",
        "x": 5,
        "baseline": 71.608,
        "fromBottom": 8.392,
        "anchor": "bottom",
        "align": "left",
        "size": 8,
        "caps": false,
        "accent": true,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Vieilles Vignes"
      },
      {
        "fields": [
          "regionCountry"
        ],
        "role": "small",
        "x": 94.6,
        "baseline": 71.608,
        "fromBottom": 8.392,
        "anchor": "bottom",
        "align": "right",
        "size": 8,
        "caps": false,
        "accent": true,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Bordeaux, France"
      },
      {
        "fields": [
          "wineTypeLine"
        ],
        "role": "small",
        "x": 5,
        "baseline": 75.138,
        "fromBottom": 4.862,
        "anchor": "bottom",
        "align": "left",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Dry Red Wine"
      },
      {
        "fields": [
          "alcVol"
        ],
        "role": "small",
        "x": 94.6,
        "baseline": 75.138,
        "fromBottom": 4.862,
        "anchor": "bottom",
        "align": "right",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Alc.: 13.5% / 750 ml."
      },
      {
        "fields": [
          "vintage"
        ],
        "role": "secondary",
        "x": 50,
        "baseline": 75.291,
        "fromBottom": 4.709,
        "anchor": "bottom",
        "align": "center",
        "size": 13,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "2018"
      }
    ]
  },
  {
    "id": "t03",
    "band": "classical",
    "refW": 100,
    "refH": 80,
    "art": {
      "kind": "rect",
      "x": 0,
      "y": 22.691,
      "w": 100,
      "h": 38.664
    },
    "texts": [
      {
        "fields": [
          "producer"
        ],
        "role": "secondary",
        "x": 50,
        "baseline": 7.15,
        "fromBottom": 72.85,
        "anchor": "top",
        "align": "center",
        "size": 9.01,
        "caps": true,
        "accent": false,
        "tracking": 0.22,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "GRAND VIN"
      },
      {
        "fields": [
          "wineName"
        ],
        "role": "hero",
        "x": 50,
        "baseline": 14.248,
        "fromBottom": 65.752,
        "anchor": "top",
        "align": "center",
        "size": 18,
        "caps": true,
        "accent": true,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "CHÂTEAU MARGAUX"
      },
      {
        "fields": [
          "appellation"
        ],
        "role": "secondary",
        "x": 50,
        "baseline": 19.368,
        "fromBottom": 60.632,
        "anchor": "top",
        "align": "center",
        "size": 12,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "Margaux AOC"
      },
      {
        "fields": [
          "classification"
        ],
        "role": "small",
        "x": 50,
        "baseline": 65.737,
        "fromBottom": 14.263,
        "anchor": "bottom",
        "align": "center",
        "size": 10,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Premier Grand Cru Classé"
      },
      {
        "fields": [
          "grape"
        ],
        "role": "small",
        "x": 50,
        "baseline": 68.915,
        "fromBottom": 11.085,
        "anchor": "bottom",
        "align": "center",
        "size": 7,
        "caps": false,
        "accent": true,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "Cabernet Sauvignon, Merlot"
      },
      {
        "fields": [
          "special"
        ],
        "role": "small",
        "x": 5,
        "baseline": 71.255,
        "fromBottom": 8.745,
        "anchor": "bottom",
        "align": "left",
        "size": 8,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Vieilles Vignes"
      },
      {
        "fields": [
          "regionCountry"
        ],
        "role": "small",
        "x": 94.6,
        "baseline": 71.255,
        "fromBottom": 8.745,
        "anchor": "bottom",
        "align": "right",
        "size": 8,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Bordeaux, France"
      },
      {
        "fields": [
          "wineTypeLine"
        ],
        "role": "small",
        "x": 5,
        "baseline": 74.785,
        "fromBottom": 5.215,
        "anchor": "bottom",
        "align": "left",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Dry Red Wine"
      },
      {
        "fields": [
          "alcVol"
        ],
        "role": "small",
        "x": 94.601,
        "baseline": 74.785,
        "fromBottom": 5.215,
        "anchor": "bottom",
        "align": "right",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Alc.: 13.5% / 750 ml."
      },
      {
        "fields": [
          "vintage"
        ],
        "role": "secondary",
        "x": 50,
        "baseline": 74.938,
        "fromBottom": 5.062,
        "anchor": "bottom",
        "align": "center",
        "size": 13,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "2018"
      }
    ]
  },
  {
    "id": "t04",
    "band": "classical",
    "refW": 100,
    "refH": 80,
    "art": {
      "kind": "rect",
      "x": 0,
      "y": 38.456,
      "w": 100,
      "h": 41.544
    },
    "texts": [
      {
        "fields": [
          "producer"
        ],
        "role": "secondary",
        "x": 50,
        "baseline": 7.15,
        "fromBottom": 72.85,
        "anchor": "top",
        "align": "center",
        "size": 9.01,
        "caps": true,
        "accent": false,
        "tracking": 0.22,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "GRAND VIN"
      },
      {
        "fields": [
          "wineName"
        ],
        "role": "hero",
        "x": 50,
        "baseline": 14.248,
        "fromBottom": 65.752,
        "anchor": "top",
        "align": "center",
        "size": 18,
        "caps": true,
        "accent": true,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "CHÂTEAU MARGAUX"
      },
      {
        "fields": [
          "appellation"
        ],
        "role": "secondary",
        "x": 50,
        "baseline": 19.368,
        "fromBottom": 60.632,
        "anchor": "top",
        "align": "center",
        "size": 12,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "Margaux AOC"
      },
      {
        "fields": [
          "classification"
        ],
        "role": "small",
        "x": 50,
        "baseline": 25.658,
        "fromBottom": 54.342,
        "anchor": "top",
        "align": "center",
        "size": 10,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Premier Grand Cru Classé"
      },
      {
        "fields": [
          "grape"
        ],
        "role": "small",
        "x": 50,
        "baseline": 28.836,
        "fromBottom": 51.164,
        "anchor": "top",
        "align": "center",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "Cabernet Sauvignon, Merlot"
      },
      {
        "fields": [
          "special"
        ],
        "role": "small",
        "x": 5,
        "baseline": 31.175,
        "fromBottom": 48.825,
        "anchor": "top",
        "align": "left",
        "size": 8,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Vieilles Vignes"
      },
      {
        "fields": [
          "regionCountry"
        ],
        "role": "small",
        "x": 94.6,
        "baseline": 31.175,
        "fromBottom": 48.825,
        "anchor": "top",
        "align": "right",
        "size": 8,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Bordeaux, France"
      },
      {
        "fields": [
          "wineTypeLine"
        ],
        "role": "small",
        "x": 5,
        "baseline": 34.705,
        "fromBottom": 45.295,
        "anchor": "top",
        "align": "left",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Dry Red Wine"
      },
      {
        "fields": [
          "alcVol"
        ],
        "role": "small",
        "x": 94.601,
        "baseline": 34.705,
        "fromBottom": 45.295,
        "anchor": "top",
        "align": "right",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Alc.: 13.5% / 750 ml."
      },
      {
        "fields": [
          "vintage"
        ],
        "role": "secondary",
        "x": 50,
        "baseline": 34.858,
        "fromBottom": 45.142,
        "anchor": "top",
        "align": "center",
        "size": 13,
        "caps": false,
        "accent": true,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "2018"
      }
    ]
  },
  {
    "id": "t05",
    "band": "free",
    "refW": 100,
    "refH": 80,
    "art": {
      "kind": "oval",
      "x": 11.127,
      "y": 21.733,
      "w": 77.747,
      "h": 37.118
    },
    "texts": [
      {
        "fields": [
          "producer"
        ],
        "role": "secondary",
        "x": 50,
        "baseline": 7.082,
        "fromBottom": 72.918,
        "anchor": "top",
        "align": "center",
        "size": 9.01,
        "caps": true,
        "accent": false,
        "tracking": 0.22,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "GRAND VIN"
      },
      {
        "fields": [
          "wineName"
        ],
        "role": "hero",
        "x": 50,
        "baseline": 23.392,
        "fromBottom": 56.608,
        "anchor": "top",
        "align": "center",
        "size": 18.68,
        "caps": true,
        "accent": true,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "CHÂTEAU MARGAUX",
        "arc": {
          "cx": 50.12,
          "cy": 96.016,
          "r": 80.171,
          "up": true,
          "sweep": 48.84
        }
      },
      {
        "fields": [
          "vintage"
        ],
        "role": "secondary",
        "x": 50,
        "baseline": 64.509,
        "fromBottom": 15.491,
        "anchor": "bottom",
        "align": "center",
        "size": 13,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "2018"
      },
      {
        "fields": [
          "grape"
        ],
        "role": "small",
        "x": 50,
        "baseline": 70.554,
        "fromBottom": 9.446,
        "anchor": "bottom",
        "align": "center",
        "size": 10,
        "caps": false,
        "accent": true,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "Cabernet Sauvignon"
      },
      {
        "fields": [
          "special"
        ],
        "role": "small",
        "x": 5,
        "baseline": 70.565,
        "fromBottom": 9.435,
        "anchor": "bottom",
        "align": "left",
        "size": 8,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "Vieilles Vignes"
      },
      {
        "fields": [
          "regionCountry"
        ],
        "role": "small",
        "x": 94.954,
        "baseline": 70.565,
        "fromBottom": 9.435,
        "anchor": "bottom",
        "align": "right",
        "size": 8,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "Bordeaux, France"
      },
      {
        "fields": [
          "classification"
        ],
        "role": "small",
        "x": 50,
        "baseline": 74.713,
        "fromBottom": 5.287,
        "anchor": "bottom",
        "align": "center",
        "size": 10,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Premier Grand Cru Classé"
      },
      {
        "fields": [
          "wineTypeLine"
        ],
        "role": "small",
        "x": 5,
        "baseline": 74.713,
        "fromBottom": 5.287,
        "anchor": "bottom",
        "align": "left",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Dry Red Wine"
      },
      {
        "fields": [
          "alcVol"
        ],
        "role": "small",
        "x": 94.601,
        "baseline": 74.713,
        "fromBottom": 5.287,
        "anchor": "bottom",
        "align": "right",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Alc.: 13.5% / 750 ml."
      }
    ]
  },
  {
    "id": "t06",
    "band": "contemporary",
    "refW": 100,
    "refH": 80,
    "art": {
      "kind": "oval",
      "x": 17.072,
      "y": 7.903,
      "w": 65.855,
      "h": 40.683
    },
    "texts": [
      {
        "fields": [
          "producer"
        ],
        "role": "secondary",
        "x": 4.955,
        "baseline": 54.094,
        "fromBottom": 25.906,
        "anchor": "bottom",
        "align": "left",
        "size": 9.01,
        "caps": true,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "GRAND VIN"
      },
      {
        "fields": [
          "appellation"
        ],
        "role": "secondary",
        "x": 95,
        "baseline": 54.142,
        "fromBottom": 25.858,
        "anchor": "bottom",
        "align": "right",
        "size": 9.01,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Margaux AOC"
      },
      {
        "fields": [
          "wineName"
        ],
        "role": "hero",
        "x": 4.602,
        "baseline": 60.84,
        "fromBottom": 19.16,
        "anchor": "bottom",
        "align": "left",
        "size": 14,
        "caps": true,
        "accent": true,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "CHÂTEAU MARGAUX"
      },
      {
        "fields": [
          "vintage"
        ],
        "role": "secondary",
        "x": 94.966,
        "baseline": 60.84,
        "fromBottom": 19.16,
        "anchor": "bottom",
        "align": "right",
        "size": 14,
        "caps": false,
        "accent": true,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "2018"
      },
      {
        "fields": [
          "special"
        ],
        "role": "small",
        "x": 94.875,
        "baseline": 65.899,
        "fromBottom": 14.101,
        "anchor": "bottom",
        "align": "right",
        "size": 8,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Vieilles Vignes"
      },
      {
        "fields": [
          "classification"
        ],
        "role": "small",
        "x": 4.955,
        "baseline": 65.9,
        "fromBottom": 14.1,
        "anchor": "bottom",
        "align": "left",
        "size": 10,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Premier Grand Cru Classé"
      },
      {
        "fields": [
          "grape"
        ],
        "role": "small",
        "x": 4.955,
        "baseline": 69.077,
        "fromBottom": 10.923,
        "anchor": "bottom",
        "align": "left",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "Cabernet Sauvignon, Merlot"
      },
      {
        "fields": [
          "regionCountry"
        ],
        "role": "small",
        "x": 94.6,
        "baseline": 69.077,
        "fromBottom": 10.923,
        "anchor": "bottom",
        "align": "right",
        "size": 8,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Bordeaux, France"
      },
      {
        "fields": [
          "wineTypeLine"
        ],
        "role": "small",
        "x": 4.955,
        "baseline": 74.241,
        "fromBottom": 5.759,
        "anchor": "bottom",
        "align": "left",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Dry Red Wine"
      },
      {
        "fields": [
          "alcVol"
        ],
        "role": "small",
        "x": 94.601,
        "baseline": 74.241,
        "fromBottom": 5.759,
        "anchor": "bottom",
        "align": "right",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Alc.: 13.5% / 750 ml."
      }
    ]
  },
  {
    "id": "t07",
    "band": "contemporary",
    "refW": 100,
    "refH": 80,
    "art": {
      "kind": "oval",
      "x": 17.072,
      "y": 20.831,
      "w": 65.855,
      "h": 40.683
    },
    "texts": [
      {
        "fields": [
          "producer"
        ],
        "role": "secondary",
        "x": 4.602,
        "baseline": 7.149,
        "fromBottom": 72.851,
        "anchor": "top",
        "align": "left",
        "size": 9.01,
        "caps": true,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "GRAND VIN"
      },
      {
        "fields": [
          "appellation"
        ],
        "role": "secondary",
        "x": 94.876,
        "baseline": 7.197,
        "fromBottom": 72.803,
        "anchor": "top",
        "align": "right",
        "size": 9.01,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Margaux AOC"
      },
      {
        "fields": [
          "wineName"
        ],
        "role": "hero",
        "x": 4.602,
        "baseline": 13.542,
        "fromBottom": 66.458,
        "anchor": "top",
        "align": "left",
        "size": 14,
        "caps": true,
        "accent": true,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "CHÂTEAU MARGAUX"
      },
      {
        "fields": [
          "vintage"
        ],
        "role": "secondary",
        "x": 94.875,
        "baseline": 13.542,
        "fromBottom": 66.458,
        "anchor": "top",
        "align": "right",
        "size": 14,
        "caps": false,
        "accent": true,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "2018"
      },
      {
        "fields": [
          "classification"
        ],
        "role": "small",
        "x": 4.601,
        "baseline": 67.105,
        "fromBottom": 12.895,
        "anchor": "bottom",
        "align": "left",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "Premier Grand Cru Classé"
      },
      {
        "fields": [
          "regionCountry"
        ],
        "role": "small",
        "x": 94.877,
        "baseline": 67.105,
        "fromBottom": 12.895,
        "anchor": "bottom",
        "align": "right",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "Bordeaux, France"
      },
      {
        "fields": [
          "grape"
        ],
        "role": "small",
        "x": 4.601,
        "baseline": 70.636,
        "fromBottom": 9.364,
        "anchor": "bottom",
        "align": "left",
        "size": 8,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Cabernet Sauvignon"
      },
      {
        "fields": [
          "special"
        ],
        "role": "small",
        "x": 94.875,
        "baseline": 70.636,
        "fromBottom": 9.364,
        "anchor": "bottom",
        "align": "right",
        "size": 8,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Vieilles Vignes"
      },
      {
        "fields": [
          "wineTypeLine"
        ],
        "role": "small",
        "x": 4.601,
        "baseline": 74.384,
        "fromBottom": 5.616,
        "anchor": "bottom",
        "align": "left",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Dry Red Wine"
      },
      {
        "fields": [
          "alcVol"
        ],
        "role": "small",
        "x": 94.876,
        "baseline": 74.384,
        "fromBottom": 5.616,
        "anchor": "bottom",
        "align": "right",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Alc.: 13.5% / 750 ml."
      }
    ]
  },
  {
    "id": "t08",
    "band": "contemporary",
    "refW": 100,
    "refH": 80,
    "art": {
      "kind": "rect",
      "x": 0,
      "y": 30.134,
      "w": 100,
      "h": 49.866
    },
    "texts": [
      {
        "fields": [
          "producer"
        ],
        "role": "secondary",
        "x": 4.955,
        "baseline": 7.149,
        "fromBottom": 72.851,
        "anchor": "top",
        "align": "left",
        "size": 9.01,
        "caps": true,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "GRAND VIN"
      },
      {
        "fields": [
          "appellation"
        ],
        "role": "secondary",
        "x": 95,
        "baseline": 7.197,
        "fromBottom": 72.803,
        "anchor": "top",
        "align": "right",
        "size": 9.01,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Margaux AOC"
      },
      {
        "fields": [
          "wineName"
        ],
        "role": "hero",
        "x": 4.602,
        "baseline": 13.895,
        "fromBottom": 66.105,
        "anchor": "top",
        "align": "left",
        "size": 14,
        "caps": true,
        "accent": true,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "CHÂTEAU MARGAUX"
      },
      {
        "fields": [
          "vintage"
        ],
        "role": "secondary",
        "x": 94.966,
        "baseline": 13.895,
        "fromBottom": 66.105,
        "anchor": "top",
        "align": "right",
        "size": 14,
        "caps": false,
        "accent": true,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "2018"
      },
      {
        "fields": [
          "special"
        ],
        "role": "small",
        "x": 94.875,
        "baseline": 18.955,
        "fromBottom": 61.045,
        "anchor": "top",
        "align": "right",
        "size": 8,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Vieilles Vignes"
      },
      {
        "fields": [
          "classification"
        ],
        "role": "small",
        "x": 4.955,
        "baseline": 18.955,
        "fromBottom": 61.045,
        "anchor": "top",
        "align": "left",
        "size": 10,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Premier Grand Cru Classé"
      },
      {
        "fields": [
          "grape"
        ],
        "role": "small",
        "x": 4.955,
        "baseline": 22.133,
        "fromBottom": 57.867,
        "anchor": "top",
        "align": "left",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "Cabernet Sauvignon, Merlot"
      },
      {
        "fields": [
          "regionCountry"
        ],
        "role": "small",
        "x": 94.6,
        "baseline": 22.133,
        "fromBottom": 57.867,
        "anchor": "top",
        "align": "right",
        "size": 8,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Bordeaux, France"
      },
      {
        "fields": [
          "wineTypeLine"
        ],
        "role": "small",
        "x": 4.955,
        "baseline": 27.296,
        "fromBottom": 52.704,
        "anchor": "top",
        "align": "left",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Dry Red Wine"
      },
      {
        "fields": [
          "alcVol"
        ],
        "role": "small",
        "x": 94.601,
        "baseline": 27.296,
        "fromBottom": 52.704,
        "anchor": "top",
        "align": "right",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Alc.: 13.5% / 750 ml."
      }
    ]
  },
  {
    "id": "t09",
    "band": "contemporary",
    "refW": 100,
    "refH": 80,
    "art": {
      "kind": "rect",
      "x": 0,
      "y": 0,
      "w": 100,
      "h": 50.095
    },
    "texts": [
      {
        "fields": [
          "producer"
        ],
        "role": "secondary",
        "x": 4.955,
        "baseline": 54.094,
        "fromBottom": 25.906,
        "anchor": "bottom",
        "align": "left",
        "size": 9.01,
        "caps": true,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "GRAND VIN"
      },
      {
        "fields": [
          "appellation"
        ],
        "role": "secondary",
        "x": 95,
        "baseline": 54.142,
        "fromBottom": 25.858,
        "anchor": "bottom",
        "align": "right",
        "size": 9.01,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Margaux AOC"
      },
      {
        "fields": [
          "wineName"
        ],
        "role": "hero",
        "x": 4.602,
        "baseline": 60.839,
        "fromBottom": 19.161,
        "anchor": "bottom",
        "align": "left",
        "size": 14,
        "caps": true,
        "accent": true,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "CHÂTEAU MARGAUX"
      },
      {
        "fields": [
          "vintage"
        ],
        "role": "secondary",
        "x": 94.966,
        "baseline": 60.84,
        "fromBottom": 19.16,
        "anchor": "bottom",
        "align": "right",
        "size": 14,
        "caps": false,
        "accent": true,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "2018"
      },
      {
        "fields": [
          "special"
        ],
        "role": "small",
        "x": 94.875,
        "baseline": 65.899,
        "fromBottom": 14.101,
        "anchor": "bottom",
        "align": "right",
        "size": 8,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Vieilles Vignes"
      },
      {
        "fields": [
          "classification"
        ],
        "role": "small",
        "x": 4.955,
        "baseline": 65.9,
        "fromBottom": 14.1,
        "anchor": "bottom",
        "align": "left",
        "size": 10,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Premier Grand Cru Classé"
      },
      {
        "fields": [
          "grape"
        ],
        "role": "small",
        "x": 4.955,
        "baseline": 69.077,
        "fromBottom": 10.923,
        "anchor": "bottom",
        "align": "left",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "Cabernet Sauvignon, Merlot"
      },
      {
        "fields": [
          "regionCountry"
        ],
        "role": "small",
        "x": 94.6,
        "baseline": 69.077,
        "fromBottom": 10.923,
        "anchor": "bottom",
        "align": "right",
        "size": 8,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Bordeaux, France"
      },
      {
        "fields": [
          "wineTypeLine"
        ],
        "role": "small",
        "x": 4.955,
        "baseline": 74.241,
        "fromBottom": 5.759,
        "anchor": "bottom",
        "align": "left",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Dry Red Wine"
      },
      {
        "fields": [
          "alcVol"
        ],
        "role": "small",
        "x": 94.601,
        "baseline": 74.241,
        "fromBottom": 5.759,
        "anchor": "bottom",
        "align": "right",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Alc.: 13.5% / 750 ml."
      }
    ]
  },
  {
    "id": "t10",
    "band": "contemporary",
    "refW": 100,
    "refH": 80,
    "art": {
      "kind": "rect",
      "x": 0,
      "y": 17.086,
      "w": 100,
      "h": 44.965
    },
    "texts": [
      {
        "fields": [
          "producer"
        ],
        "role": "secondary",
        "x": 4.602,
        "baseline": 7.149,
        "fromBottom": 72.851,
        "anchor": "top",
        "align": "left",
        "size": 9.01,
        "caps": true,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "GRAND VIN"
      },
      {
        "fields": [
          "appellation"
        ],
        "role": "secondary",
        "x": 94.876,
        "baseline": 7.197,
        "fromBottom": 72.803,
        "anchor": "top",
        "align": "right",
        "size": 9.01,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Margaux AOC"
      },
      {
        "fields": [
          "wineName"
        ],
        "role": "hero",
        "x": 4.602,
        "baseline": 13.542,
        "fromBottom": 66.458,
        "anchor": "top",
        "align": "left",
        "size": 14,
        "caps": true,
        "accent": true,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "CHÂTEAU MARGAUX"
      },
      {
        "fields": [
          "vintage"
        ],
        "role": "secondary",
        "x": 94.875,
        "baseline": 13.542,
        "fromBottom": 66.458,
        "anchor": "top",
        "align": "right",
        "size": 14,
        "caps": false,
        "accent": true,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "2018"
      },
      {
        "fields": [
          "classification"
        ],
        "role": "small",
        "x": 4.601,
        "baseline": 67.105,
        "fromBottom": 12.895,
        "anchor": "bottom",
        "align": "left",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "Premier Grand Cru Classé"
      },
      {
        "fields": [
          "regionCountry"
        ],
        "role": "small",
        "x": 94.877,
        "baseline": 67.105,
        "fromBottom": 12.895,
        "anchor": "bottom",
        "align": "right",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "Bordeaux, France"
      },
      {
        "fields": [
          "grape"
        ],
        "role": "small",
        "x": 4.601,
        "baseline": 70.636,
        "fromBottom": 9.364,
        "anchor": "bottom",
        "align": "left",
        "size": 8,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Cabernet Sauvignon"
      },
      {
        "fields": [
          "special"
        ],
        "role": "small",
        "x": 94.875,
        "baseline": 70.636,
        "fromBottom": 9.364,
        "anchor": "bottom",
        "align": "right",
        "size": 8,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Vieilles Vignes"
      },
      {
        "fields": [
          "wineTypeLine"
        ],
        "role": "small",
        "x": 4.601,
        "baseline": 74.384,
        "fromBottom": 5.616,
        "anchor": "bottom",
        "align": "left",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Dry Red Wine"
      },
      {
        "fields": [
          "alcVol"
        ],
        "role": "small",
        "x": 94.876,
        "baseline": 74.384,
        "fromBottom": 5.616,
        "anchor": "bottom",
        "align": "right",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Alc.: 13.5% / 750 ml."
      }
    ]
  },
  {
    "id": "t11",
    "band": "free",
    "refW": 100,
    "refH": 80,
    "art": {
      "kind": "rect",
      "x": 0,
      "y": 0,
      "w": 68.779,
      "h": 80
    },
    "texts": [
      {
        "fields": [
          "vintage"
        ],
        "role": "secondary",
        "x": 75.115,
        "baseline": 14.512,
        "fromBottom": 65.488,
        "anchor": "top",
        "align": "left",
        "size": 14,
        "caps": false,
        "accent": true,
        "tracking": 0,
        "rot": -90,
        "serif": true,
        "bold": true,
        "sample": "2018"
      },
      {
        "fields": [
          "wineName"
        ],
        "role": "hero",
        "x": 75.051,
        "baseline": 74.947,
        "fromBottom": 5.053,
        "anchor": "bottom",
        "align": "left",
        "size": 12,
        "caps": true,
        "accent": true,
        "tracking": 0,
        "rot": -90,
        "serif": true,
        "bold": true,
        "sample": "CHÂTEAU MARGAUX"
      },
      {
        "fields": [
          "producer"
        ],
        "role": "secondary",
        "x": 78.861,
        "baseline": 74.947,
        "fromBottom": 5.053,
        "anchor": "bottom",
        "align": "left",
        "size": 9,
        "caps": true,
        "accent": false,
        "tracking": 0,
        "rot": -90,
        "serif": true,
        "bold": false,
        "sample": "GRAND VIN"
      },
      {
        "fields": [
          "appellation"
        ],
        "role": "secondary",
        "x": 84.371,
        "baseline": 74.947,
        "fromBottom": 5.053,
        "anchor": "bottom",
        "align": "left",
        "size": 9.01,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": -90,
        "serif": true,
        "bold": true,
        "sample": "Margaux AOC"
      },
      {
        "fields": [
          "classification"
        ],
        "role": "small",
        "x": 87.758,
        "baseline": 74.947,
        "fromBottom": 5.053,
        "anchor": "bottom",
        "align": "left",
        "size": 8,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": -90,
        "serif": true,
        "bold": false,
        "sample": "Premier Grand Cru Classé"
      },
      {
        "fields": [
          "regionCountry",
          "grape"
        ],
        "join": " / ",
        "role": "small",
        "x": 91.144,
        "baseline": 74.947,
        "fromBottom": 5.053,
        "anchor": "bottom",
        "align": "left",
        "size": 8,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": -90,
        "serif": true,
        "bold": false,
        "sample": "Bordeaux, France / Cabernet Sauvignon, Merlot"
      },
      {
        "fields": [
          "special",
          "wineTypeLine",
          "alcVol"
        ],
        "join": " / ",
        "role": "small",
        "x": 94.108,
        "baseline": 74.947,
        "fromBottom": 5.053,
        "anchor": "bottom",
        "align": "left",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": -90,
        "serif": true,
        "bold": false,
        "sample": "Vieilles Vignes / Dry Red Wine / Alc.: 13.5% / 750 ml."
      }
    ]
  },
  {
    "id": "t12",
    "band": "free",
    "refW": 100,
    "refH": 80,
    "art": {
      "kind": "rect",
      "x": 31.222,
      "y": 0,
      "w": 68.778,
      "h": 80
    },
    "texts": [
      {
        "fields": [
          "vintage"
        ],
        "role": "secondary",
        "x": 8.44,
        "baseline": 14.512,
        "fromBottom": 65.488,
        "anchor": "top",
        "align": "left",
        "size": 14,
        "caps": false,
        "accent": true,
        "tracking": 0,
        "rot": -90,
        "serif": true,
        "bold": true,
        "sample": "2018"
      },
      {
        "fields": [
          "wineName"
        ],
        "role": "hero",
        "x": 8.376,
        "baseline": 74.947,
        "fromBottom": 5.053,
        "anchor": "bottom",
        "align": "left",
        "size": 12,
        "caps": true,
        "accent": true,
        "tracking": 0,
        "rot": -90,
        "serif": true,
        "bold": true,
        "sample": "CHÂTEAU MARGAUX"
      },
      {
        "fields": [
          "producer"
        ],
        "role": "secondary",
        "x": 12.186,
        "baseline": 74.947,
        "fromBottom": 5.053,
        "anchor": "bottom",
        "align": "left",
        "size": 9,
        "caps": true,
        "accent": false,
        "tracking": 0,
        "rot": -90,
        "serif": true,
        "bold": false,
        "sample": "GRAND VIN"
      },
      {
        "fields": [
          "appellation"
        ],
        "role": "secondary",
        "x": 17.696,
        "baseline": 74.947,
        "fromBottom": 5.053,
        "anchor": "bottom",
        "align": "left",
        "size": 9.01,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": -90,
        "serif": true,
        "bold": true,
        "sample": "Margaux AOC"
      },
      {
        "fields": [
          "classification"
        ],
        "role": "small",
        "x": 21.083,
        "baseline": 74.947,
        "fromBottom": 5.053,
        "anchor": "bottom",
        "align": "left",
        "size": 8,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": -90,
        "serif": true,
        "bold": false,
        "sample": "Premier Grand Cru Classé"
      },
      {
        "fields": [
          "regionCountry",
          "grape"
        ],
        "join": " / ",
        "role": "small",
        "x": 24.469,
        "baseline": 74.947,
        "fromBottom": 5.053,
        "anchor": "bottom",
        "align": "left",
        "size": 8,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": -90,
        "serif": true,
        "bold": false,
        "sample": "Bordeaux, France / Cabernet Sauvignon, Merlot"
      },
      {
        "fields": [
          "special",
          "wineTypeLine",
          "alcVol"
        ],
        "join": " / ",
        "role": "small",
        "x": 27.433,
        "baseline": 74.947,
        "fromBottom": 5.053,
        "anchor": "bottom",
        "align": "left",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": -90,
        "serif": true,
        "bold": false,
        "sample": "Vieilles Vignes / Dry Red Wine / Alc.: 13.5% / 750 ml."
      }
    ]
  }
];
