/* GENERATED by tools/extract-templates.mjs from the owner's
   Layout_Options.pdf — do not edit by hand. Re-run the tool when he
   re-draws a template. Millimetres, measured from the label's TOP-LEFT;
   sizes in points at the reference size. */

import type { Template } from "./templates";

export const TEMPLATES: Template[] = [
  {
    "id": "t01",
    "band": "classical",
    "refW": 104,
    "refH": 84,
    "art": {
      "kind": "rect",
      "x": 0,
      "y": 0,
      "w": 104,
      "h": 41.149
    },
    "texts": [
      {
        "fields": [
          "producer"
        ],
        "role": "secondary",
        "x": 52,
        "baseline": 48.226,
        "fromBottom": 35.774,
        "anchor": "bottom",
        "align": "center",
        "size": 13.01,
        "caps": true,
        "accent": false,
        "tracking": 0.22,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "GRAND VIN"
      },
      {
        "fields": [
          "wineName"
        ],
        "role": "hero",
        "x": 52,
        "baseline": 56.03,
        "fromBottom": 27.97,
        "anchor": "bottom",
        "align": "center",
        "size": 20,
        "caps": true,
        "accent": true,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "CHÂTEAU MARGAUX"
      },
      {
        "fields": [
          "appellation"
        ],
        "role": "secondary",
        "x": 52,
        "baseline": 61.855,
        "fromBottom": 22.145,
        "anchor": "bottom",
        "align": "center",
        "size": 14,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "Margaux AOC"
      },
      {
        "fields": [
          "classification"
        ],
        "role": "small",
        "x": 52,
        "baseline": 67.385,
        "fromBottom": 16.615,
        "anchor": "bottom",
        "align": "center",
        "size": 10,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Premier Grand Cru Classé"
      },
      {
        "fields": [
          "grape"
        ],
        "role": "small",
        "x": 52,
        "baseline": 70.562,
        "fromBottom": 13.438,
        "anchor": "bottom",
        "align": "center",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "Cabernet Sauvignon, Merlot"
      },
      {
        "fields": [
          "special"
        ],
        "role": "small",
        "x": 7,
        "baseline": 73.607,
        "fromBottom": 10.392,
        "anchor": "bottom",
        "align": "left",
        "size": 8,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Vieilles Vignes"
      },
      {
        "fields": [
          "regionCountry"
        ],
        "role": "small",
        "x": 96.6,
        "baseline": 73.607,
        "fromBottom": 10.392,
        "anchor": "bottom",
        "align": "right",
        "size": 8,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Bordeaux, France"
      },
      {
        "fields": [
          "wineTypeLine"
        ],
        "role": "small",
        "x": 7,
        "baseline": 77.137,
        "fromBottom": 6.862,
        "anchor": "bottom",
        "align": "left",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Dry Red Wine"
      },
      {
        "fields": [
          "alcVol"
        ],
        "role": "small",
        "x": 96.6,
        "baseline": 77.137,
        "fromBottom": 6.862,
        "anchor": "bottom",
        "align": "right",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Alc.: 13.5% / 750 ml."
      },
      {
        "fields": [
          "vintage"
        ],
        "role": "secondary",
        "x": 52,
        "baseline": 77.29,
        "fromBottom": 6.709,
        "anchor": "bottom",
        "align": "center",
        "size": 13,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "2018"
      }
    ]
  },
  {
    "id": "t02",
    "band": "classical",
    "refW": 104,
    "refH": 84,
    "art": {
      "kind": "oval",
      "x": 18.231,
      "y": 12.534,
      "w": 67.537,
      "h": 36.509
    },
    "texts": [
      {
        "fields": [
          "producer"
        ],
        "role": "secondary",
        "x": 52,
        "baseline": 11.136,
        "fromBottom": 72.864,
        "anchor": "top",
        "align": "center",
        "size": 10.03,
        "caps": true,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "GRAND VIN",
        "arc": {
          "cx": 51.999,
          "cy": 76.727,
          "r": 66.885,
          "up": true,
          "sweep": 22.49
        }
      },
      {
        "fields": [
          "wineName"
        ],
        "role": "hero",
        "x": 52,
        "baseline": 56.03,
        "fromBottom": 27.97,
        "anchor": "bottom",
        "align": "center",
        "size": 16,
        "caps": true,
        "accent": true,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "CHÂTEAU MARGAUX"
      },
      {
        "fields": [
          "appellation"
        ],
        "role": "secondary",
        "x": 52,
        "baseline": 61.502,
        "fromBottom": 22.498,
        "anchor": "bottom",
        "align": "center",
        "size": 14,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "Margaux AOC"
      },
      {
        "fields": [
          "classification"
        ],
        "role": "small",
        "x": 52,
        "baseline": 67.385,
        "fromBottom": 16.615,
        "anchor": "bottom",
        "align": "center",
        "size": 10,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Premier Grand Cru Classé"
      },
      {
        "fields": [
          "grape"
        ],
        "role": "small",
        "x": 52,
        "baseline": 70.562,
        "fromBottom": 13.438,
        "anchor": "bottom",
        "align": "center",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "Cabernet Sauvignon, Merlot"
      },
      {
        "fields": [
          "special"
        ],
        "role": "small",
        "x": 7,
        "baseline": 73.607,
        "fromBottom": 10.392,
        "anchor": "bottom",
        "align": "left",
        "size": 8,
        "caps": false,
        "accent": true,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Vieilles Vignes"
      },
      {
        "fields": [
          "regionCountry"
        ],
        "role": "small",
        "x": 96.6,
        "baseline": 73.607,
        "fromBottom": 10.392,
        "anchor": "bottom",
        "align": "right",
        "size": 8,
        "caps": false,
        "accent": true,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Bordeaux, France"
      },
      {
        "fields": [
          "wineTypeLine"
        ],
        "role": "small",
        "x": 7,
        "baseline": 77.137,
        "fromBottom": 6.862,
        "anchor": "bottom",
        "align": "left",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Dry Red Wine"
      },
      {
        "fields": [
          "alcVol"
        ],
        "role": "small",
        "x": 96.6,
        "baseline": 77.137,
        "fromBottom": 6.862,
        "anchor": "bottom",
        "align": "right",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Alc.: 13.5% / 750 ml."
      },
      {
        "fields": [
          "vintage"
        ],
        "role": "secondary",
        "x": 52,
        "baseline": 77.29,
        "fromBottom": 6.709,
        "anchor": "bottom",
        "align": "center",
        "size": 13,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "2018"
      }
    ]
  },
  {
    "id": "t03",
    "band": "classical",
    "refW": 104,
    "refH": 84,
    "art": {
      "kind": "rect",
      "x": 0,
      "y": 24.691,
      "w": 104,
      "h": 38.664
    },
    "texts": [
      {
        "fields": [
          "producer"
        ],
        "role": "secondary",
        "x": 52,
        "baseline": 9.15,
        "fromBottom": 74.85,
        "anchor": "top",
        "align": "center",
        "size": 9.01,
        "caps": true,
        "accent": false,
        "tracking": 0.22,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "GRAND VIN"
      },
      {
        "fields": [
          "wineName"
        ],
        "role": "hero",
        "x": 52,
        "baseline": 16.248,
        "fromBottom": 67.752,
        "anchor": "top",
        "align": "center",
        "size": 18,
        "caps": true,
        "accent": true,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "CHÂTEAU MARGAUX"
      },
      {
        "fields": [
          "appellation"
        ],
        "role": "secondary",
        "x": 52,
        "baseline": 21.368,
        "fromBottom": 62.632,
        "anchor": "top",
        "align": "center",
        "size": 12,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "Margaux AOC"
      },
      {
        "fields": [
          "classification"
        ],
        "role": "small",
        "x": 52,
        "baseline": 67.737,
        "fromBottom": 16.263,
        "anchor": "bottom",
        "align": "center",
        "size": 10,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Premier Grand Cru Classé"
      },
      {
        "fields": [
          "grape"
        ],
        "role": "small",
        "x": 52,
        "baseline": 70.915,
        "fromBottom": 13.085,
        "anchor": "bottom",
        "align": "center",
        "size": 7,
        "caps": false,
        "accent": true,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "Cabernet Sauvignon, Merlot"
      },
      {
        "fields": [
          "special"
        ],
        "role": "small",
        "x": 7,
        "baseline": 73.255,
        "fromBottom": 10.745,
        "anchor": "bottom",
        "align": "left",
        "size": 8,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Vieilles Vignes"
      },
      {
        "fields": [
          "regionCountry"
        ],
        "role": "small",
        "x": 96.6,
        "baseline": 73.255,
        "fromBottom": 10.745,
        "anchor": "bottom",
        "align": "right",
        "size": 8,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Bordeaux, France"
      },
      {
        "fields": [
          "wineTypeLine"
        ],
        "role": "small",
        "x": 7,
        "baseline": 76.785,
        "fromBottom": 7.215,
        "anchor": "bottom",
        "align": "left",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Dry Red Wine"
      },
      {
        "fields": [
          "alcVol"
        ],
        "role": "small",
        "x": 96.601,
        "baseline": 76.785,
        "fromBottom": 7.215,
        "anchor": "bottom",
        "align": "right",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Alc.: 13.5% / 750 ml."
      },
      {
        "fields": [
          "vintage"
        ],
        "role": "secondary",
        "x": 52,
        "baseline": 76.938,
        "fromBottom": 7.062,
        "anchor": "bottom",
        "align": "center",
        "size": 13,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "2018"
      }
    ]
  },
  {
    "id": "t04",
    "band": "classical",
    "refW": 104,
    "refH": 84,
    "art": {
      "kind": "rect",
      "x": 0,
      "y": 40.456,
      "w": 104,
      "h": 43.544
    },
    "texts": [
      {
        "fields": [
          "producer"
        ],
        "role": "secondary",
        "x": 52,
        "baseline": 9.15,
        "fromBottom": 74.85,
        "anchor": "top",
        "align": "center",
        "size": 9.01,
        "caps": true,
        "accent": false,
        "tracking": 0.22,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "GRAND VIN"
      },
      {
        "fields": [
          "wineName"
        ],
        "role": "hero",
        "x": 52,
        "baseline": 16.248,
        "fromBottom": 67.752,
        "anchor": "top",
        "align": "center",
        "size": 18,
        "caps": true,
        "accent": true,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "CHÂTEAU MARGAUX"
      },
      {
        "fields": [
          "appellation"
        ],
        "role": "secondary",
        "x": 52,
        "baseline": 21.368,
        "fromBottom": 62.632,
        "anchor": "top",
        "align": "center",
        "size": 12,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "Margaux AOC"
      },
      {
        "fields": [
          "classification"
        ],
        "role": "small",
        "x": 52,
        "baseline": 27.658,
        "fromBottom": 56.342,
        "anchor": "top",
        "align": "center",
        "size": 10,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Premier Grand Cru Classé"
      },
      {
        "fields": [
          "grape"
        ],
        "role": "small",
        "x": 52,
        "baseline": 30.836,
        "fromBottom": 53.164,
        "anchor": "top",
        "align": "center",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "Cabernet Sauvignon, Merlot"
      },
      {
        "fields": [
          "special"
        ],
        "role": "small",
        "x": 7,
        "baseline": 33.175,
        "fromBottom": 50.825,
        "anchor": "top",
        "align": "left",
        "size": 8,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Vieilles Vignes"
      },
      {
        "fields": [
          "regionCountry"
        ],
        "role": "small",
        "x": 96.6,
        "baseline": 33.175,
        "fromBottom": 50.825,
        "anchor": "top",
        "align": "right",
        "size": 8,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Bordeaux, France"
      },
      {
        "fields": [
          "wineTypeLine"
        ],
        "role": "small",
        "x": 7,
        "baseline": 36.705,
        "fromBottom": 47.295,
        "anchor": "top",
        "align": "left",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Dry Red Wine"
      },
      {
        "fields": [
          "alcVol"
        ],
        "role": "small",
        "x": 96.601,
        "baseline": 36.705,
        "fromBottom": 47.295,
        "anchor": "top",
        "align": "right",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Alc.: 13.5% / 750 ml."
      },
      {
        "fields": [
          "vintage"
        ],
        "role": "secondary",
        "x": 52,
        "baseline": 36.858,
        "fromBottom": 47.142,
        "anchor": "top",
        "align": "center",
        "size": 13,
        "caps": false,
        "accent": true,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "2018"
      }
    ]
  },
  {
    "id": "t05",
    "band": "free",
    "refW": 104,
    "refH": 84,
    "art": {
      "kind": "oval",
      "x": 13.127,
      "y": 23.733,
      "w": 77.747,
      "h": 37.118
    },
    "texts": [
      {
        "fields": [
          "producer"
        ],
        "role": "secondary",
        "x": 52,
        "baseline": 9.082,
        "fromBottom": 74.918,
        "anchor": "top",
        "align": "center",
        "size": 9.01,
        "caps": true,
        "accent": false,
        "tracking": 0.22,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "GRAND VIN"
      },
      {
        "fields": [
          "wineName"
        ],
        "role": "hero",
        "x": 52,
        "baseline": 25.392,
        "fromBottom": 58.608,
        "anchor": "top",
        "align": "center",
        "size": 18.68,
        "caps": true,
        "accent": true,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "CHÂTEAU MARGAUX",
        "arc": {
          "cx": 52.12,
          "cy": 98.016,
          "r": 80.171,
          "up": true,
          "sweep": 48.84
        }
      },
      {
        "fields": [
          "vintage"
        ],
        "role": "secondary",
        "x": 52,
        "baseline": 66.509,
        "fromBottom": 17.491,
        "anchor": "bottom",
        "align": "center",
        "size": 13,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "2018"
      },
      {
        "fields": [
          "grape"
        ],
        "role": "small",
        "x": 52,
        "baseline": 72.554,
        "fromBottom": 11.446,
        "anchor": "bottom",
        "align": "center",
        "size": 10,
        "caps": false,
        "accent": true,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "Cabernet Sauvignon"
      },
      {
        "fields": [
          "special"
        ],
        "role": "small",
        "x": 7,
        "baseline": 72.565,
        "fromBottom": 11.435,
        "anchor": "bottom",
        "align": "left",
        "size": 8,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "Vieilles Vignes"
      },
      {
        "fields": [
          "regionCountry"
        ],
        "role": "small",
        "x": 96.954,
        "baseline": 72.565,
        "fromBottom": 11.435,
        "anchor": "bottom",
        "align": "right",
        "size": 8,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "Bordeaux, France"
      },
      {
        "fields": [
          "classification"
        ],
        "role": "small",
        "x": 52,
        "baseline": 76.713,
        "fromBottom": 7.287,
        "anchor": "bottom",
        "align": "center",
        "size": 10,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Premier Grand Cru Classé"
      },
      {
        "fields": [
          "wineTypeLine"
        ],
        "role": "small",
        "x": 7,
        "baseline": 76.713,
        "fromBottom": 7.287,
        "anchor": "bottom",
        "align": "left",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Dry Red Wine"
      },
      {
        "fields": [
          "alcVol"
        ],
        "role": "small",
        "x": 96.601,
        "baseline": 76.713,
        "fromBottom": 7.287,
        "anchor": "bottom",
        "align": "right",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Alc.: 13.5% / 750 ml."
      }
    ]
  },
  {
    "id": "t06",
    "band": "contemporary",
    "refW": 104,
    "refH": 84,
    "art": {
      "kind": "oval",
      "x": 19.072,
      "y": 9.903,
      "w": 65.855,
      "h": 40.683
    },
    "texts": [
      {
        "fields": [
          "producer"
        ],
        "role": "secondary",
        "x": 6.955,
        "baseline": 56.094,
        "fromBottom": 27.906,
        "anchor": "bottom",
        "align": "left",
        "size": 9.01,
        "caps": true,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "GRAND VIN"
      },
      {
        "fields": [
          "appellation"
        ],
        "role": "secondary",
        "x": 97,
        "baseline": 56.142,
        "fromBottom": 27.858,
        "anchor": "bottom",
        "align": "right",
        "size": 9.01,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Margaux AOC"
      },
      {
        "fields": [
          "wineName"
        ],
        "role": "hero",
        "x": 6.602,
        "baseline": 62.839,
        "fromBottom": 21.16,
        "anchor": "bottom",
        "align": "left",
        "size": 14,
        "caps": true,
        "accent": true,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "CHÂTEAU MARGAUX"
      },
      {
        "fields": [
          "vintage"
        ],
        "role": "secondary",
        "x": 96.966,
        "baseline": 62.84,
        "fromBottom": 21.16,
        "anchor": "bottom",
        "align": "right",
        "size": 14,
        "caps": false,
        "accent": true,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "2018"
      },
      {
        "fields": [
          "special"
        ],
        "role": "small",
        "x": 96.875,
        "baseline": 67.899,
        "fromBottom": 16.101,
        "anchor": "bottom",
        "align": "right",
        "size": 8,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Vieilles Vignes"
      },
      {
        "fields": [
          "classification"
        ],
        "role": "small",
        "x": 6.955,
        "baseline": 67.899,
        "fromBottom": 16.1,
        "anchor": "bottom",
        "align": "left",
        "size": 10,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Premier Grand Cru Classé"
      },
      {
        "fields": [
          "grape"
        ],
        "role": "small",
        "x": 6.955,
        "baseline": 71.077,
        "fromBottom": 12.923,
        "anchor": "bottom",
        "align": "left",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "Cabernet Sauvignon, Merlot"
      },
      {
        "fields": [
          "regionCountry"
        ],
        "role": "small",
        "x": 96.6,
        "baseline": 71.077,
        "fromBottom": 12.923,
        "anchor": "bottom",
        "align": "right",
        "size": 8,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Bordeaux, France"
      },
      {
        "fields": [
          "wineTypeLine"
        ],
        "role": "small",
        "x": 6.955,
        "baseline": 76.241,
        "fromBottom": 7.759,
        "anchor": "bottom",
        "align": "left",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Dry Red Wine"
      },
      {
        "fields": [
          "alcVol"
        ],
        "role": "small",
        "x": 96.601,
        "baseline": 76.241,
        "fromBottom": 7.759,
        "anchor": "bottom",
        "align": "right",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Alc.: 13.5% / 750 ml."
      }
    ]
  },
  {
    "id": "t07",
    "band": "contemporary",
    "refW": 104,
    "refH": 84,
    "art": {
      "kind": "oval",
      "x": 19.072,
      "y": 22.831,
      "w": 65.855,
      "h": 40.683
    },
    "texts": [
      {
        "fields": [
          "producer"
        ],
        "role": "secondary",
        "x": 6.602,
        "baseline": 9.149,
        "fromBottom": 74.851,
        "anchor": "top",
        "align": "left",
        "size": 9.01,
        "caps": true,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "GRAND VIN"
      },
      {
        "fields": [
          "appellation"
        ],
        "role": "secondary",
        "x": 96.876,
        "baseline": 9.197,
        "fromBottom": 74.803,
        "anchor": "top",
        "align": "right",
        "size": 9.01,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Margaux AOC"
      },
      {
        "fields": [
          "wineName"
        ],
        "role": "hero",
        "x": 6.602,
        "baseline": 15.542,
        "fromBottom": 68.458,
        "anchor": "top",
        "align": "left",
        "size": 14,
        "caps": true,
        "accent": true,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "CHÂTEAU MARGAUX"
      },
      {
        "fields": [
          "vintage"
        ],
        "role": "secondary",
        "x": 96.875,
        "baseline": 15.542,
        "fromBottom": 68.458,
        "anchor": "top",
        "align": "right",
        "size": 14,
        "caps": false,
        "accent": true,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "2018"
      },
      {
        "fields": [
          "classification"
        ],
        "role": "small",
        "x": 6.601,
        "baseline": 69.105,
        "fromBottom": 14.895,
        "anchor": "bottom",
        "align": "left",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "Premier Grand Cru Classé"
      },
      {
        "fields": [
          "regionCountry"
        ],
        "role": "small",
        "x": 96.877,
        "baseline": 69.105,
        "fromBottom": 14.895,
        "anchor": "bottom",
        "align": "right",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "Bordeaux, France"
      },
      {
        "fields": [
          "grape"
        ],
        "role": "small",
        "x": 6.601,
        "baseline": 72.636,
        "fromBottom": 11.364,
        "anchor": "bottom",
        "align": "left",
        "size": 8,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Cabernet Sauvignon"
      },
      {
        "fields": [
          "special"
        ],
        "role": "small",
        "x": 96.875,
        "baseline": 72.636,
        "fromBottom": 11.364,
        "anchor": "bottom",
        "align": "right",
        "size": 8,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Vieilles Vignes"
      },
      {
        "fields": [
          "wineTypeLine"
        ],
        "role": "small",
        "x": 6.601,
        "baseline": 76.384,
        "fromBottom": 7.616,
        "anchor": "bottom",
        "align": "left",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Dry Red Wine"
      },
      {
        "fields": [
          "alcVol"
        ],
        "role": "small",
        "x": 96.876,
        "baseline": 76.384,
        "fromBottom": 7.616,
        "anchor": "bottom",
        "align": "right",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Alc.: 13.5% / 750 ml."
      }
    ]
  },
  {
    "id": "t08",
    "band": "contemporary",
    "refW": 104,
    "refH": 84,
    "art": {
      "kind": "rect",
      "x": 0,
      "y": 32.134,
      "w": 104,
      "h": 51.866
    },
    "texts": [
      {
        "fields": [
          "producer"
        ],
        "role": "secondary",
        "x": 6.955,
        "baseline": 9.149,
        "fromBottom": 74.851,
        "anchor": "top",
        "align": "left",
        "size": 9.01,
        "caps": true,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "GRAND VIN"
      },
      {
        "fields": [
          "appellation"
        ],
        "role": "secondary",
        "x": 97,
        "baseline": 9.197,
        "fromBottom": 74.803,
        "anchor": "top",
        "align": "right",
        "size": 9.01,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Margaux AOC"
      },
      {
        "fields": [
          "wineName"
        ],
        "role": "hero",
        "x": 6.602,
        "baseline": 15.895,
        "fromBottom": 68.105,
        "anchor": "top",
        "align": "left",
        "size": 14,
        "caps": true,
        "accent": true,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "CHÂTEAU MARGAUX"
      },
      {
        "fields": [
          "vintage"
        ],
        "role": "secondary",
        "x": 96.966,
        "baseline": 15.895,
        "fromBottom": 68.105,
        "anchor": "top",
        "align": "right",
        "size": 14,
        "caps": false,
        "accent": true,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "2018"
      },
      {
        "fields": [
          "special"
        ],
        "role": "small",
        "x": 96.875,
        "baseline": 20.955,
        "fromBottom": 63.045,
        "anchor": "top",
        "align": "right",
        "size": 8,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Vieilles Vignes"
      },
      {
        "fields": [
          "classification"
        ],
        "role": "small",
        "x": 6.955,
        "baseline": 20.955,
        "fromBottom": 63.045,
        "anchor": "top",
        "align": "left",
        "size": 10,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Premier Grand Cru Classé"
      },
      {
        "fields": [
          "grape"
        ],
        "role": "small",
        "x": 6.955,
        "baseline": 24.132,
        "fromBottom": 59.867,
        "anchor": "top",
        "align": "left",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "Cabernet Sauvignon, Merlot"
      },
      {
        "fields": [
          "regionCountry"
        ],
        "role": "small",
        "x": 96.6,
        "baseline": 24.133,
        "fromBottom": 59.867,
        "anchor": "top",
        "align": "right",
        "size": 8,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Bordeaux, France"
      },
      {
        "fields": [
          "wineTypeLine"
        ],
        "role": "small",
        "x": 6.955,
        "baseline": 29.296,
        "fromBottom": 54.704,
        "anchor": "top",
        "align": "left",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Dry Red Wine"
      },
      {
        "fields": [
          "alcVol"
        ],
        "role": "small",
        "x": 96.601,
        "baseline": 29.296,
        "fromBottom": 54.704,
        "anchor": "top",
        "align": "right",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Alc.: 13.5% / 750 ml."
      }
    ]
  },
  {
    "id": "t09",
    "band": "contemporary",
    "refW": 104,
    "refH": 84,
    "art": {
      "kind": "rect",
      "x": 0,
      "y": 0,
      "w": 104,
      "h": 52.095
    },
    "texts": [
      {
        "fields": [
          "producer"
        ],
        "role": "secondary",
        "x": 6.955,
        "baseline": 56.094,
        "fromBottom": 27.906,
        "anchor": "bottom",
        "align": "left",
        "size": 9.01,
        "caps": true,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "GRAND VIN"
      },
      {
        "fields": [
          "appellation"
        ],
        "role": "secondary",
        "x": 97,
        "baseline": 56.142,
        "fromBottom": 27.858,
        "anchor": "bottom",
        "align": "right",
        "size": 9.01,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Margaux AOC"
      },
      {
        "fields": [
          "wineName"
        ],
        "role": "hero",
        "x": 6.602,
        "baseline": 62.839,
        "fromBottom": 21.161,
        "anchor": "bottom",
        "align": "left",
        "size": 14,
        "caps": true,
        "accent": true,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "CHÂTEAU MARGAUX"
      },
      {
        "fields": [
          "vintage"
        ],
        "role": "secondary",
        "x": 96.966,
        "baseline": 62.84,
        "fromBottom": 21.16,
        "anchor": "bottom",
        "align": "right",
        "size": 14,
        "caps": false,
        "accent": true,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "2018"
      },
      {
        "fields": [
          "special"
        ],
        "role": "small",
        "x": 96.875,
        "baseline": 67.899,
        "fromBottom": 16.101,
        "anchor": "bottom",
        "align": "right",
        "size": 8,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Vieilles Vignes"
      },
      {
        "fields": [
          "classification"
        ],
        "role": "small",
        "x": 6.955,
        "baseline": 67.899,
        "fromBottom": 16.1,
        "anchor": "bottom",
        "align": "left",
        "size": 10,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Premier Grand Cru Classé"
      },
      {
        "fields": [
          "grape"
        ],
        "role": "small",
        "x": 6.955,
        "baseline": 71.077,
        "fromBottom": 12.923,
        "anchor": "bottom",
        "align": "left",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "Cabernet Sauvignon, Merlot"
      },
      {
        "fields": [
          "regionCountry"
        ],
        "role": "small",
        "x": 96.6,
        "baseline": 71.077,
        "fromBottom": 12.923,
        "anchor": "bottom",
        "align": "right",
        "size": 8,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Bordeaux, France"
      },
      {
        "fields": [
          "wineTypeLine"
        ],
        "role": "small",
        "x": 6.955,
        "baseline": 76.241,
        "fromBottom": 7.759,
        "anchor": "bottom",
        "align": "left",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Dry Red Wine"
      },
      {
        "fields": [
          "alcVol"
        ],
        "role": "small",
        "x": 96.601,
        "baseline": 76.241,
        "fromBottom": 7.759,
        "anchor": "bottom",
        "align": "right",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Alc.: 13.5% / 750 ml."
      }
    ]
  },
  {
    "id": "t10",
    "band": "contemporary",
    "refW": 104,
    "refH": 84,
    "art": {
      "kind": "rect",
      "x": 0,
      "y": 19.086,
      "w": 104,
      "h": 44.965
    },
    "texts": [
      {
        "fields": [
          "producer"
        ],
        "role": "secondary",
        "x": 6.602,
        "baseline": 9.149,
        "fromBottom": 74.851,
        "anchor": "top",
        "align": "left",
        "size": 9.01,
        "caps": true,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "GRAND VIN"
      },
      {
        "fields": [
          "appellation"
        ],
        "role": "secondary",
        "x": 96.876,
        "baseline": 9.197,
        "fromBottom": 74.803,
        "anchor": "top",
        "align": "right",
        "size": 9.01,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Margaux AOC"
      },
      {
        "fields": [
          "wineName"
        ],
        "role": "hero",
        "x": 6.602,
        "baseline": 15.542,
        "fromBottom": 68.458,
        "anchor": "top",
        "align": "left",
        "size": 14,
        "caps": true,
        "accent": true,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "CHÂTEAU MARGAUX"
      },
      {
        "fields": [
          "vintage"
        ],
        "role": "secondary",
        "x": 96.875,
        "baseline": 15.542,
        "fromBottom": 68.458,
        "anchor": "top",
        "align": "right",
        "size": 14,
        "caps": false,
        "accent": true,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "2018"
      },
      {
        "fields": [
          "classification"
        ],
        "role": "small",
        "x": 6.601,
        "baseline": 69.105,
        "fromBottom": 14.895,
        "anchor": "bottom",
        "align": "left",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "Premier Grand Cru Classé"
      },
      {
        "fields": [
          "regionCountry"
        ],
        "role": "small",
        "x": 96.877,
        "baseline": 69.105,
        "fromBottom": 14.895,
        "anchor": "bottom",
        "align": "right",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": true,
        "sample": "Bordeaux, France"
      },
      {
        "fields": [
          "grape"
        ],
        "role": "small",
        "x": 6.601,
        "baseline": 72.636,
        "fromBottom": 11.364,
        "anchor": "bottom",
        "align": "left",
        "size": 8,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Cabernet Sauvignon"
      },
      {
        "fields": [
          "special"
        ],
        "role": "small",
        "x": 96.875,
        "baseline": 72.636,
        "fromBottom": 11.364,
        "anchor": "bottom",
        "align": "right",
        "size": 8,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Vieilles Vignes"
      },
      {
        "fields": [
          "wineTypeLine"
        ],
        "role": "small",
        "x": 6.601,
        "baseline": 76.384,
        "fromBottom": 7.616,
        "anchor": "bottom",
        "align": "left",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Dry Red Wine"
      },
      {
        "fields": [
          "alcVol"
        ],
        "role": "small",
        "x": 96.876,
        "baseline": 76.384,
        "fromBottom": 7.616,
        "anchor": "bottom",
        "align": "right",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": 0,
        "serif": true,
        "bold": false,
        "sample": "Alc.: 13.5% / 750 ml."
      }
    ]
  },
  {
    "id": "t11",
    "band": "free",
    "refW": 104,
    "refH": 84,
    "art": {
      "kind": "rect",
      "x": 0,
      "y": 0,
      "w": 70.779,
      "h": 84
    },
    "texts": [
      {
        "fields": [
          "vintage"
        ],
        "role": "secondary",
        "x": 77.115,
        "baseline": 16.512,
        "fromBottom": 67.488,
        "anchor": "top",
        "align": "left",
        "size": 14,
        "caps": false,
        "accent": true,
        "tracking": 0,
        "rot": -90,
        "serif": true,
        "bold": true,
        "sample": "2018"
      },
      {
        "fields": [
          "wineName"
        ],
        "role": "hero",
        "x": 77.051,
        "baseline": 76.947,
        "fromBottom": 7.053,
        "anchor": "bottom",
        "align": "left",
        "size": 12,
        "caps": true,
        "accent": true,
        "tracking": 0,
        "rot": -90,
        "serif": true,
        "bold": true,
        "sample": "CHÂTEAU MARGAUX"
      },
      {
        "fields": [
          "producer"
        ],
        "role": "secondary",
        "x": 80.861,
        "baseline": 76.947,
        "fromBottom": 7.053,
        "anchor": "bottom",
        "align": "left",
        "size": 9,
        "caps": true,
        "accent": false,
        "tracking": 0,
        "rot": -90,
        "serif": true,
        "bold": false,
        "sample": "GRAND VIN"
      },
      {
        "fields": [
          "appellation"
        ],
        "role": "secondary",
        "x": 86.371,
        "baseline": 76.947,
        "fromBottom": 7.053,
        "anchor": "bottom",
        "align": "left",
        "size": 9.01,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": -90,
        "serif": true,
        "bold": true,
        "sample": "Margaux AOC"
      },
      {
        "fields": [
          "classification"
        ],
        "role": "small",
        "x": 89.758,
        "baseline": 76.947,
        "fromBottom": 7.053,
        "anchor": "bottom",
        "align": "left",
        "size": 8,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": -90,
        "serif": true,
        "bold": false,
        "sample": "Premier Grand Cru Classé"
      },
      {
        "fields": [
          "regionCountry",
          "grape"
        ],
        "join": " / ",
        "role": "small",
        "x": 93.144,
        "baseline": 76.947,
        "fromBottom": 7.053,
        "anchor": "bottom",
        "align": "left",
        "size": 8,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": -90,
        "serif": true,
        "bold": false,
        "sample": "Bordeaux, France / Cabernet Sauvignon, Merlot"
      },
      {
        "fields": [
          "special",
          "wineTypeLine",
          "alcVol"
        ],
        "join": " / ",
        "role": "small",
        "x": 96.108,
        "baseline": 76.947,
        "fromBottom": 7.053,
        "anchor": "bottom",
        "align": "left",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": -90,
        "serif": true,
        "bold": false,
        "sample": "Vieilles Vignes / Dry Red Wine / Alc.: 13.5% / 750 ml."
      }
    ]
  },
  {
    "id": "t12",
    "band": "free",
    "refW": 104,
    "refH": 84,
    "art": {
      "kind": "rect",
      "x": 33.222,
      "y": 0,
      "w": 70.779,
      "h": 84
    },
    "texts": [
      {
        "fields": [
          "vintage"
        ],
        "role": "secondary",
        "x": 10.44,
        "baseline": 16.512,
        "fromBottom": 67.488,
        "anchor": "top",
        "align": "left",
        "size": 14,
        "caps": false,
        "accent": true,
        "tracking": 0,
        "rot": -90,
        "serif": true,
        "bold": true,
        "sample": "2018"
      },
      {
        "fields": [
          "wineName"
        ],
        "role": "hero",
        "x": 10.376,
        "baseline": 76.947,
        "fromBottom": 7.053,
        "anchor": "bottom",
        "align": "left",
        "size": 12,
        "caps": true,
        "accent": true,
        "tracking": 0,
        "rot": -90,
        "serif": true,
        "bold": true,
        "sample": "CHÂTEAU MARGAUX"
      },
      {
        "fields": [
          "producer"
        ],
        "role": "secondary",
        "x": 14.186,
        "baseline": 76.947,
        "fromBottom": 7.053,
        "anchor": "bottom",
        "align": "left",
        "size": 9,
        "caps": true,
        "accent": false,
        "tracking": 0,
        "rot": -90,
        "serif": true,
        "bold": false,
        "sample": "GRAND VIN"
      },
      {
        "fields": [
          "appellation"
        ],
        "role": "secondary",
        "x": 19.696,
        "baseline": 76.947,
        "fromBottom": 7.053,
        "anchor": "bottom",
        "align": "left",
        "size": 9.01,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": -90,
        "serif": true,
        "bold": true,
        "sample": "Margaux AOC"
      },
      {
        "fields": [
          "classification"
        ],
        "role": "small",
        "x": 23.083,
        "baseline": 76.947,
        "fromBottom": 7.053,
        "anchor": "bottom",
        "align": "left",
        "size": 8,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": -90,
        "serif": true,
        "bold": false,
        "sample": "Premier Grand Cru Classé"
      },
      {
        "fields": [
          "regionCountry",
          "grape"
        ],
        "join": " / ",
        "role": "small",
        "x": 26.469,
        "baseline": 76.947,
        "fromBottom": 7.053,
        "anchor": "bottom",
        "align": "left",
        "size": 8,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": -90,
        "serif": true,
        "bold": false,
        "sample": "Bordeaux, France / Cabernet Sauvignon, Merlot"
      },
      {
        "fields": [
          "special",
          "wineTypeLine",
          "alcVol"
        ],
        "join": " / ",
        "role": "small",
        "x": 29.433,
        "baseline": 76.947,
        "fromBottom": 7.053,
        "anchor": "bottom",
        "align": "left",
        "size": 7,
        "caps": false,
        "accent": false,
        "tracking": 0,
        "rot": -90,
        "serif": true,
        "bold": false,
        "sample": "Vieilles Vignes / Dry Red Wine / Alc.: 13.5% / 750 ml."
      }
    ]
  }
];
