/* THE ABOUT US PAGE (owner, 2026-09-30): his own text, in the third person (his request) — the Georgian is
   Claude's translation for him to correct. The founders' photos live at
   public/newui/about/giorgi.jpg and levan.jpg (grey until they come). */
export const ABOUT_EN: string[] = [
 "With over twenty years in visual communication, Giorgi Popiashvili has worked across art direction, design, and film, with his work recognized at Cannes, the London International Awards, and other international festivals. After designing dozens of wine brands and packaging, he completed a sommelier course and found himself deeply immersed in the magical world of wine. Working closely with mostly small, natural winemakers, he became familiar with a simple problem: for small producers or small batches, creating good packaging and bringing a bottle to market can be too much of a commitment.",
 "While completing his MFA in Painting in New York, he reconnected with his longtime friend and colleague Levan Lepsveridze, a longtime creative-industry leader and Cannes Lions representative in Georgia. Throughout his career, Levan has been awarded at numerous international festivals and has served on juries for many international award shows. They are both from Georgia — a country with an 8,000-year winemaking tradition and some of the earliest known evidence of wine production. Their shared background, experience, and perspective led to the idea for this platform.",
 "The platform uses advanced technology, including generative AI, supported by a smart architecture that helps winemakers turn a few words about their wine into the basic elements they need to bring a bottle to market — from labels and bottle visuals to product pages and marketing materials — in minutes.",
 "But technology is only a tool. They use it to give more space to human creativity and to help tell human stories. That is why the platform works with the visual languages of real artists — from historical masters to contemporary artists working with them — bringing human artistic vision into the heart of the technology."
];
export const ABOUT_GE: string[] = [
 "ვიზუალურ კომუნიკაციაში ოცწლიანი გამოცდილებით გიორგი პოპიაშვილი მუშაობდა არტ-დირექციის, დიზაინისა და კინოს მიმართულებით, მისი ნამუშევრები აღიარებულია კანში, London International Awards-ზე და სხვა საერთაშორისო ფესტივალებზე. ათობით ღვინის ბრენდისა და შეფუთვის შექმნის შემდეგ მან სომელიეს კურსი გაიარა და ღვინის ჯადოსნურ სამყაროში ღრმად ჩაეფლო. უმეტესად მცირე, ნატურალური ღვინის მწარმოებლებთან მჭიდრო თანამშრომლობისას ის ერთ მარტივ პრობლემას გაეცნო: მცირე მწარმოებლისთვის ან მცირე პარტიისთვის კარგი შეფუთვის შექმნა და ბოთლის ბაზარზე გატანა ზედმეტად დიდი ვალდებულება შეიძლება იყოს.",
 "ნიუ-იორკში ფერწერის მაგისტრატურის (MFA) დასრულებისას ის კვლავ დაუკავშირდა თავის დიდი ხნის მეგობარსა და კოლეგას, ლევან ლეფსვერიძეს — შემოქმედებითი ინდუსტრიის დიდი ხნის ლიდერსა და Cannes Lions-ის წარმომადგენელს საქართველოში. კარიერის განმავლობაში ლევანი მრავალ საერთაშორისო ფესტივალზე დაჯილდოვდა და არაერთი საერთაშორისო კონკურსის ჟიურის წევრი იყო. ორივენი საქართველოდან არიან — ქვეყნიდან, რომელსაც ღვინის დაყენების 8000-წლიანი ტრადიცია და ღვინის წარმოების ერთ-ერთი უძველესი ცნობილი კვალი აქვს. მათმა საერთო წარსულმა, გამოცდილებამ და ხედვამ ამ პლატფორმის იდეამდე მიიყვანა.",
 "პლატფორმა იყენებს თანამედროვე ტექნოლოგიებს, მათ შორის გენერაციულ ხელოვნურ ინტელექტს, ჭკვიანი არქიტექტურით, რომელიც ღვინის მწარმოებლებს ეხმარება, ღვინოზე რამდენიმე სიტყვა წუთებში აქციონ იმ ძირითად ელემენტებად, რაც ბოთლის ბაზარზე გასატანად სჭირდებათ — ეტიკეტებიდან და ბოთლის ვიზუალებიდან პროდუქტის გვერდებამდე და მარკეტინგულ მასალებამდე.",
 "მაგრამ ტექნოლოგია მხოლოდ ინსტრუმენტია. ისინი მას იმისთვის იყენებენ, რომ ადამიანის შემოქმედებას მეტი სივრცე მისცენ და ადამიანური ისტორიების მოყოლაში დაეხმარონ. სწორედ ამიტომ პლატფორმა ნამდვილი არტისტების ვიზუალურ ენებთან მუშაობს — ისტორიული ოსტატებიდან მათთან მომუშავე თანამედროვე არტისტებამდე — და ადამიანის მხატვრულ ხედვას ტექნოლოგიის გულში აყენებს."
];
export const FOUNDERS = [
  { name: "Giorgi Popiashvili", nameGe: "გიორგი პოპიაშვილი", photo: "/newui/about/giorgi.jpg", pos: "50% 28%" },
  { name: "Levan Lepsveridze", nameGe: "ლევან ლეფსვერიძე", photo: "/newui/about/levan.jpg", pos: "50% 22%" },
];
