/* THE ABOUT US PAGE (owner, 2026-09-30): his own text — the Georgian is
   Claude's translation for him to correct. The founders' photos live at
   public/newui/about/giorgi.jpg and levan.jpg (grey until they come). */
export const ABOUT_EN: string[] = [
 "With over twenty years in visual communication, I have worked across art direction, design, and film, with my work recognized at Cannes, the London International Awards, and other international festivals. After designing dozens of wine brands and packaging, I completed a sommelier course and found myself deeply immersed in the magical world of wine. Working closely with mostly small, natural winemakers, I became familiar with a simple problem: for small producers or small batches, creating good packaging and bringing a bottle to market can be too much of a commitment.",
 "While completing my MFA in Painting in New York, I reconnected with my longtime friend and colleague Levan Lepsveridze, a longtime creative-industry leader and Cannes Lions representative in Georgia. Throughout his career, Levan has been awarded at numerous international festivals and has served on juries for many international award shows. We are both from Georgia — a country with an 8,000-year winemaking tradition and some of the earliest known evidence of wine production. Our shared background, experience, and perspective led to the idea for this platform.",
 "We use advanced technology, including generative AI, supported by a smart architecture that helps winemakers turn a few words about their wine into the basic elements they need to bring a bottle to market — from labels and bottle visuals to product pages and marketing materials — in minutes.",
 "But technology is only a tool. We use it to give more space to human creativity and to help tell human stories. That is why our platform works with the visual languages of real artists — from historical masters to contemporary artists working with us — bringing human artistic vision into the heart of the technology."
];
export const ABOUT_GE: string[] = [
 "ვიზუალურ კომუნიკაციაში ოცწლიანი გამოცდილებით ვმუშაობდი არტ-დირექციის, დიზაინისა და კინოს მიმართულებით, ჩემი ნამუშევრები აღიარებულია კანში, London International Awards-ზე და სხვა საერთაშორისო ფესტივალებზე. ათობით ღვინის ბრენდისა და შეფუთვის შექმნის შემდეგ სომელიეს კურსი გავიარე და ღვინის ჯადოსნურ სამყაროში ღრმად ჩავეფალი. უმეტესად მცირე, ნატურალური ღვინის მწარმოებლებთან მჭიდრო თანამშრომლობისას ერთ მარტივ პრობლემას გავეცანი: მცირე მწარმოებლისთვის ან მცირე პარტიისთვის კარგი შეფუთვის შექმნა და ბოთლის ბაზარზე გატანა ზედმეტად დიდი ვალდებულება შეიძლება იყოს.",
 "ნიუ-იორკში ფერწერის მაგისტრატურის (MFA) დასრულებისას კვლავ დავუკავშირდი ჩემს დიდი ხნის მეგობარსა და კოლეგას, ლევან ლეფსვერიძეს — შემოქმედებითი ინდუსტრიის დიდი ხნის ლიდერსა და Cannes Lions-ის წარმომადგენელს საქართველოში. კარიერის განმავლობაში ლევანი მრავალ საერთაშორისო ფესტივალზე დაჯილდოვდა და არაერთი საერთაშორისო კონკურსის ჟიურის წევრი იყო. ორივენი საქართველოდან ვართ — ქვეყნიდან, რომელსაც ღვინის დაყენების 8000-წლიანი ტრადიცია და ღვინის წარმოების ერთ-ერთი უძველესი ცნობილი კვალი აქვს. ჩვენმა საერთო წარსულმა, გამოცდილებამ და ხედვამ ამ პლატფორმის იდეამდე მიგვიყვანა.",
 "ჩვენ ვიყენებთ თანამედროვე ტექნოლოგიებს, მათ შორის გენერაციულ ხელოვნურ ინტელექტს, ჭკვიანი არქიტექტურით, რომელიც ღვინის მწარმოებლებს ეხმარება, ღვინოზე რამდენიმე სიტყვა წუთებში აქციონ იმ ძირითად ელემენტებად, რაც ბოთლის ბაზარზე გასატანად სჭირდებათ — ეტიკეტებიდან და ბოთლის ვიზუალებიდან პროდუქტის გვერდებამდე და მარკეტინგულ მასალებამდე.",
 "მაგრამ ტექნოლოგია მხოლოდ ინსტრუმენტია. ჩვენ მას იმისთვის ვიყენებთ, რომ ადამიანის შემოქმედებას მეტი სივრცე მივცეთ და ადამიანური ისტორიების მოყოლაში დავეხმაროთ. სწორედ ამიტომ ჩვენი პლატფორმა ნამდვილი არტისტების ვიზუალურ ენებთან მუშაობს — ისტორიული ოსტატებიდან ჩვენთან მომუშავე თანამედროვე არტისტებამდე — და ადამიანის მხატვრულ ხედვას ტექნოლოგიის გულში აყენებს."
];
export const FOUNDERS = [
  { name: "Giorgi Popiashvili", nameGe: "გიორგი პოპიაშვილი", photo: "/newui/about/giorgi.jpg" },
  { name: "Levan Lepsveridze", nameGe: "ლევან ლეფსვერიძე", photo: "/newui/about/levan.jpg" },
];
